export const MOCK_BUGS = [
  {
    id: 1,
    title: "Login page fails on Safari",
    priority: "CRITICAL",
    status: "OPEN",
    assignedTo: "Ali Dev",
    projectId: 1,
    createdAt: "2026-03-01T10:00:00",
    createdBy: 1,
  },
  {
    id: 2,
    title: "Dashboard loads slowly",
    priority: "HIGH",
    status: "IN_PROGRESS",
    assignedTo: "Ali Dev",
    projectId: 1,
    createdAt: "2026-03-05T09:00:00",
    createdBy: 2,
  },
  {
    id: 3,
    title: "Export CSV broken",
    priority: "MEDIUM",
    status: "OPEN",
    assignedTo: "Sara Dev",
    projectId: 2,
    createdAt: "2026-03-10T14:00:00",
    createdBy: 2,
  },
  {
    id: 4,
    title: "Password reset email delay",
    priority: "HIGH",
    status: "RESOLVED",
    assignedTo: "Sara Dev",
    projectId: 1,
    createdAt: "2026-03-12T11:00:00",
    createdBy: 3,
  },
  {
    id: 5,
    title: "UI glitch on mobile nav",
    priority: "LOW",
    status: "CLOSED",
    assignedTo: "Ali Dev",
    projectId: 2,
    createdAt: "2026-03-15T16:00:00",
    createdBy: 1,
  },
  {
    id: 6,
    title: "Filter not resetting state",
    priority: "MEDIUM",
    status: "OPEN",
    assignedTo: "Sara Dev",
    projectId: 3,
    createdAt: "2026-03-18T08:00:00",
    createdBy: 2,
  },
  {
    id: 7,
    title: "Null pointer in bug assign",
    priority: "CRITICAL",
    status: "IN_PROGRESS",
    assignedTo: "Ali Dev",
    projectId: 1,
    createdAt: "2026-03-20T13:00:00",
    createdBy: 3,
  },
  {
    id: 8,
    title: "Pagination off by one",
    priority: "LOW",
    status: "RESOLVED",
    assignedTo: "Sara Dev",
    projectId: 2,
    createdAt: "2026-03-22T10:30:00",
    createdBy: 1,
  },
];

export const MY_BUGS = MOCK_BUGS.filter((b) => b.assignedTo === "Ali Dev");

export const MOCK_STATS = {
  totalBugs: 8,
  openBugs: 3,
  inProgress: 2,
  resolved: 2,
  closed: 1,
  critical: 2,
  high: 2,
  medium: 2,
  low: 2,
};

export const MOCK_PROJECTS = [
  { id: 1, name: "BugFlow App", bugs: 4, members: 5 },
  { id: 2, name: "Mobile Client", bugs: 3, members: 3 },
  { id: 3, name: "API Gateway", bugs: 1, members: 4 },
];
